export type WebxdcUpdate<T = unknown> = {
	payload: T;
	info?: string;
	href?: string;
	document?: string;
	summary?: string;
	notify?: Record<string, string>;
	serial: number;
	max_serial: number;
};

export type WebxdcSendUpdate<T = unknown> = Omit<WebxdcUpdate<T>, 'serial' | 'max_serial'>;

export type WebxdcSendToChatMessage = {
	text?: string;
	file?: {
		name: string;
		blob?: Blob;
		base64?: string;
		plainText?: string;
	};
};

export type WebxdcRealtimeChannel = {
	setListener: (cb: (data: Uint8Array) => void) => void;
	send: (data: Uint8Array) => void;
	leave: () => void;
};

export type WebxdcImportFilter = {
	extensions?: string[];
	mimeTypes?: string[];
	multiple?: boolean;
};

const sendQueue: WebxdcSendUpdate[] = [];
let flushTimer: number | undefined;
let lastSentAt = 0;

export function hasWebxdc(): boolean {
	return typeof window !== 'undefined' && !!window.webxdc;
}

export function hasRealtimeChannel(): boolean {
	return hasWebxdc() && typeof window.webxdc.joinRealtimeChannel === 'function';
}

export function getSendUpdateLimits() {
	if (!hasWebxdc()) {
		return {
			interval: 0,
			maxSize: 128000
		};
	}
	return {
		interval: window.webxdc.sendUpdateInterval ?? 0,
		maxSize: window.webxdc.sendUpdateMaxSize ?? 128000
	};
}

function payloadSizeBytes(update: WebxdcSendUpdate): number {
	return new TextEncoder().encode(JSON.stringify(update)).byteLength;
}

function flushSendQueue() {
	if (!hasWebxdc()) return;
	if (sendQueue.length === 0) {
		flushTimer = undefined;
		return;
	}
	const { interval, maxSize } = getSendUpdateLimits();
	const now = Date.now();
	const waitMs = interval > 0 ? Math.max(0, interval - (now - lastSentAt)) : 0;

	if (waitMs > 0) {
		flushTimer = window.setTimeout(flushSendQueue, waitMs);
		return;
	}

	const next = sendQueue.shift();
	if (!next) {
		flushTimer = undefined;
		return;
	}

	if (payloadSizeBytes(next) > maxSize) {
		console.warn('Skipped webxdc update: payload exceeds sendUpdateMaxSize', {
			maxSize
		});
	} else {
		window.webxdc.sendUpdate(next, '');
		lastSentAt = Date.now();
	}

	flushTimer = window.setTimeout(flushSendQueue, interval > 0 ? interval : 0);
}

export function sendWebxdcUpdate<T>(
	payload: T,
	options: Omit<WebxdcSendUpdate<T>, 'payload'> = {}
): void {
	if (!hasWebxdc()) return;
	sendQueue.push({
		payload,
		...options
	});
	if (flushTimer === undefined) {
		flushSendQueue();
	}
}

export function onWebxdcUpdate<T>(
	listener: (update: WebxdcUpdate<T>) => void,
	startSerial = 0
): void {
	if (!hasWebxdc()) return;
	window.webxdc.setUpdateListener((update) => listener(update as WebxdcUpdate<T>), startSerial);
}

export async function sendTextToChat(text: string): Promise<void> {
	if (!hasWebxdc()) return;
	const trimmed = text.trim();
	if (!trimmed) return;
	if (typeof window.webxdc.sendToChat !== 'function') return;
	await window.webxdc.sendToChat({ text: trimmed });
}

export async function sendTextFileToChat(name: string, content: string): Promise<void> {
	if (!hasWebxdc()) return;
	if (typeof window.webxdc.sendToChat !== 'function') return;
	await window.webxdc.sendToChat({
		file: {
			name,
			plainText: content
		},
		text: `Generated by ${window.webxdc.selfName || 'template app'}`
	});
}

export async function importWebxdcFiles(filter: WebxdcImportFilter = {}): Promise<File[]> {
	if (!hasWebxdc()) return [];
	if (typeof window.webxdc.importFiles === 'function') {
		return window.webxdc.importFiles(filter);
	}
	return new Promise((resolve) => {
		const input = document.createElement('input');
		input.type = 'file';
		input.multiple = !!filter.multiple;
		const accept = [...(filter.extensions ?? []), ...(filter.mimeTypes ?? [])].join(',');
		if (accept) input.accept = accept;
		input.onchange = () => resolve(Array.from(input.files ?? []));
		input.click();
	});
}

export function joinRealtimeChannel(
	listener: (data: Uint8Array) => void
): WebxdcRealtimeChannel | null {
	const join = window.webxdc.joinRealtimeChannel;
	if (!join) return null;
	const channel = join.call(window.webxdc);
	if (!channel) return null;
	channel.setListener(listener);
	return channel;
}

export function encodeRealtimeText(message: string): Uint8Array {
	return new TextEncoder().encode(message);
}

export function decodeRealtimeText(data: Uint8Array): string {
	return new TextDecoder().decode(data);
}
